GET http://localhost:8080/cicd/api/todos
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-06-08T115102.200.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 58
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "title 2",
  "description": "description 2"
}

<> 2024-06-08T115050.201.json

###

GET http://localhost:8080/cicd/api/todos
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-06-08T115033.200.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 58
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "title 1",
  "description": "description 1"
}

<> 2024-06-08T115002.201.json

###

GET http://localhost:8080/cicd/api/todos
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-06-08T114928.200.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 58
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "title 1",
  "description": "description 1"
}

<> 2024-05-25T115908.201.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 58
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "title 5",
  "description": "description 5"
}

<> 2024-05-22T211530.500.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 53
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": null,
  "description": "description 5"
}

<> 2024-05-11T221210.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 52
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "description 5"
}

<> 2024-05-11T221149.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 58
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "title 5",
  "description": "description 5"
}

<> 2024-05-11T221126.201.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 783
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "",
  "description": "  description 5   ",
  "_description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T220819.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 785
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": null,
  "description": "  description 5   ",
  "_description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T220807.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 783
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "",
  "description": "  description 5   ",
  "_description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T220743.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 785
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": null,
  "description": "  description 5   ",
  "_description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T220725.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 781
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": ,
  "description": "  description 5   ",
  "_description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T220708.500.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 781
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": ,
  "description": "  description 5   ",
  "_description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T220621.500.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 787
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "_title": "tNN",
  "description": "  description 5   ",
  "_description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T220608.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 787
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "_title": "tNN",
  "description": "  description 5   ",
  "_description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T220258.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 786
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "tNN",
  "description": "  description 5   ",
  "_description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T220253.201.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 784
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "  description 5   ",
  "_description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T220239.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 744
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T215429.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 746
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "  description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5   description 5 "

}

<> 2024-05-11T214112.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 52
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "description 5"
}

<> 2024-05-11T213832.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 52
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "description 5"
}

<> 2024-05-11T213823.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 52
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "description 5"
}

<> 2024-05-11T212140.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 52
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "description 5"
}

<> 2024-05-11T211830.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 52
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "description 5"
}

<> 2024-05-11T210720.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 51
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "",
  "description": "description 5"
}

<> 2024-05-11T204059.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 52
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "description 5"
}

<> 2024-05-11T204046.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 52
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "description 5"
}

<> 2024-05-11T203656.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 52
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "t",
  "description": "description 5"
}

<> 2024-05-11T203615.400.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 58
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "title 5",
  "description": "description 5"
}

<> 2024-05-11T203605.409.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 58
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "title 5",
  "description": "description 5"
}

<> 2024-05-11T203603.201.json

###

PUT http://localhost:8080/cicd/api/todos/98486688-5670-4f5b-a4e9-94570b0230eb/complete
Accept: application/json
Content-Length: 0
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T123001.404.json

###

PUT http://localhost:8080/cicd/api/todos/d7ec4eca-4234-4d66-a47c-02f3ced8bc9a/complete
Accept: application/json
Content-Length: 0
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122952.202.json

###

GET http://localhost:8080/cicd/api/todos/671aef21-1771-4a95-b8b0-f0a2fd86bfc3
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122932.404.json

###

GET http://localhost:8080/cicd/api/todos/07d37e1d-3953-44ca-a7a8-599a1c125913
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122925.404.json

###

GET http://localhost:8080/cicd/api/todos/5acf9f00-ebd2-4045-bc62-cfdef137df0a
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122913.404.json

###

GET http://localhost:8080/cicd/api/todos/d7ec4eca-4234-4d66-a47c-02f3ced8bc9a
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122900.200.json

###

GET http://localhost:8080/cicd/api/todos
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122838.200.json

###

GET http://localhost:8080/cicd/api/todos?page=5&size=1
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122825.200.json

###

GET http://localhost:8080/cicd/api/todos?page=4&size=1
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122819.200.json

###

GET http://localhost:8080/cicd/api/todos?page=0&size=1
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122800.200.json

###

GET http://localhost:8080/cicd/api/todos?page=3&size=2
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122738.200.json

###

GET http://localhost:8080/cicd/api/todos?page=1&size=2
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122731.200.json

###

GET http://localhost:8080/cicd/api/todos?page=0&size=2
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122723.200.json

###

GET http://localhost:8080/cicd/api/todos
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122655.200.json

###

GET http://localhost:8080/cicd/api/todos
Accept: application/json
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-05-11T122632.200.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 58
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "title 5",
  "description": "description 5"
}

<> 2024-05-11T122621.201.json

###

POST http://localhost:8080/cicd/api/todos
Content-Type: application/json
Accept: application/json
Content-Length: 58
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.7)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "title 4",
  "description": "description 4"
}

<> 2024-05-11T122615.201.json

###

