name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username Diangual --password ${{GHCR_PATH}} ghcr.io
        docker build . --tag ghcr.io/diangual/projet-todos:latest
        docker push ghcr.io/diangual/projet-todos:latest
